---
- '#000000'
- '#cd0000'
- '#00cd00'
- '#cdcd00'
- '#0000cd'
- '#cd00cd'
- '#00cdcd'
- '#e5e5e5'
- '#7f7f7f'
- '#ff0000'
- '#00ff00'
- '#ffff00'
- '#0000ff'
- '#ff00ff'
- '#00ffff'
- '#ffffff'
- '#000000'
- '#00008b'
- '#0000cd'
- '#0000ff'
- '#008b00'
- '#008b8b'
- '#008bcd'
- '#008bff'
- '#00cd00'
- '#00cd8b'
- '#00cdcd'
- '#00cdff'
- '#00ff00'
- '#00ff8b'
- '#00ffcd'
- '#00ffff'
- '#8b0000'
- '#8b008b'
- '#8b00cd'
- '#8b00ff'
- '#8b8b00'
- '#8b8b8b'
- '#8b8bcd'
- '#8b8bff'
- '#8bcd00'
- '#8bcd8b'
- '#8bcdcd'
- '#8bcdff'
- '#8bff00'
- '#8bff8b'
- '#8bffcd'
- '#8bffff'
- '#cd0000'
- '#cd008b'
- '#cd00cd'
- '#cd00ff'
- '#cd8b00'
- '#cd8b8b'
- '#cd8bcd'
- '#cd8bff'
- '#cdcd00'
- '#cdcd8b'
- '#cdcdcd'
- '#cdcdff'
- '#cdff00'
- '#cdff8b'
- '#cdffcd'
- '#cdffff'
- '#ff0000'
- '#ff008b'
- '#ff00cd'
- '#ff00ff'
- '#ff8b00'
- '#ff8b8b'
- '#ff8bcd'
- '#ff8bff'
- '#ffcd00'
- '#ffcd8b'
- '#ffcdcd'
- '#ffcdff'
- '#ffff00'
- '#ffff8b'
- '#ffffcd'
- '#ffffff'
- '#2e2e2e'
- '#5c5c5c'
- '#737373'
- '#8b8b8b'
- '#a2a2a2'
- '#b9b9b9'
- '#d0d0d0'
- '#e7e7e7'
